### ISSUE TITLE
Little typo

### ISSUE THREAD

**Issue by casouri** [MephistoMMM/memacs#1]
删除 paste transient state， 有 counsel-yand 和 evil-register 了，这个多此一举

In reademe

**Comment by MephistoMMM** [comment]
ok, I will correct it

**Comment by MephistoMMM** [comment]
I have modified it by `pangu-spacing-space-current-buffer`.

**Comment by casouri** [comment]
counsel-yank

**Comment by MephistoMMM** [comment]
oops...
