### ISSUE TITLE
使用company module时出现错误：Company: backend (:separate company-capf company-yasnippet) error "request cancelled"

### ISSUE THREAD

**Issue by iT-Boyer** [MephistoMMM/memacs#2]
### What did you expect to happen?

使用doom 配置了+tabnine插件，功能可以正常使用。

但是在输入字符时，出现第二次无法正常提示的情况。

### What actually happened?

第一次输入时，可以正常提示，但是第二次会出现如下错误：
```sh
Company: An error occurred in auto-begin
Company: backend (:separate company-capf company-yasnippet) error "request cancelled" with args (candidates src)
```

### Steps to reproduce

1. 生命方法
```swift
static func AllfilesOf(target:PBXTarget, srcPath:Path) -> [Path] {
        var srcfiles:[Path] = []
        //头文件+宏文件
        var headers:[Path] = []
       //此时输入hea，不提示headers全名变量
       head
}
```
此时在上述位置，输入hea，不提示headers全名变量，提示如下错误：
```sh
Company: An error occurred in auto-begin
Company: backend (:separate company-capf company-yasnippet) error "request cancelled" with args (candidates src)
```

### System Information

*

**Comment by MephistoMMM** [comment]
你是用 lsp 了吗？我看上去感觉像是 lsp 后端报的错误。

**Comment by iT-Boyer** [comment]
使用了lsp。
现象很奇怪:每次重启emacs，前几次自动补齐正常，完成一段编辑之后，就出出现request cancelled错误。

**Comment by MephistoMMM** [comment]
可以试一下以下几种debug方式：
1. 关掉 lsp 重启emacs ，检查bug是否复现
2. 换一个同类编程语言的项目，检查bug是否复现
3. 换一个不同编程语言的项目，检查bug是否复现

**Comment by iT-Boyer** [comment]
我使用的doom的内置module swift
init.el 配置
```
:lang 
 (swift 
  ;;+lsp
  )
```
注释了lsp特性，重新编译，问题还在。

以上问题，都是在输入变量名时有出现的。 . 点语句补齐是正常的。

**Comment by iT-Boyer** [comment]
我使用的doom的内置module swift
init.el 配置
```
:lang 
 (swift 
  ;;+lsp
  )
```
注释了lsp特性，重新编译，问题还在。

以上问题，都是在输入变量名时出现的。 . 点语句补齐是正常的。

**Comment by MephistoMMM** [comment]
https://github.com/emacs-lsp/lsp-mode/issues/3028

swift 的 lsp 服务端的问题，我查了一下 mr 已经被合并了，你需要更新 lsp 包

**Comment by iT-Boyer** [comment]
谢谢
确实是暂存导致的，看来暂时只能手动清理缓存来解决问题了。
```elisp
(lsp-completion--clear-cache t)
```
